server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subscriber_db
    username: postgres
    password: yourpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info
